server:
  port: 1024

db:
  type: 'postgres'
  port: 5432
  database: 'postgres'

jwt:
  expiresIn: 3600

ideamart:
  baseurl: 'http://core.sdp:7000'

app:
  id: 'APP_059278'
  password: '174fc2ff9014e2ee4b6603ea8f5d880e'