server:
  port: 1024

db:
  type: ''
  port: 5432
  database: ''
  host: ''
  username: ''
  password: ''
  synchronize: true

jwt:
  expiresIn: 21600
  secret: ''
  refreshSecret: ''

ideamart:
  baseurl: ''
  id: ''
  password: ''
  applicationMetaData:
    client: ''
    device: ''
    os: ''
    appCode: ''

mSpace:
  baseurl: ''
  id: ''
  password: ''
  applicationMetaData:
    client: ''
    device: ''
    os: ''
    appCode: ''

app:
  id: ''
  password: ''
  applicationMetaData:
    client: ''
    device: ''
    os: ''
    appCode: ''

aws:
  bucketName: ''
  endPoint: ''

admin:
  telNo: ''
  password: ''
  tokenValidity: 43200